name: Lychee Link Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --exclude 'https://www.linkedin.com/*'
            --exclude 'https://github.com/veronika1977/digital_wardrobe_team_44/.*'
            --exclude 'https://agent-6a29aac2b0946--benevolent-frangollo-a08785.netlify.app'
            './**/*.md'
          fail: true
          failIfEmpty: false
